### ISSUE TITLE
Ensure user actions have clear meaning when using capacitive module like TTP224

### ISSUE THREAD

**Issue by DerKleineLeif** [radiowewewe/Radioino#3]
Often not only a single button is pressed at the same time when using capacitive buttons like TTP224 modules for  user input. This leads to quite confusing behaveior. The goal is to ensure that user events are only triggered/ processed when over all buttons the the user meaing is clear.

**Comment by wmarkow** [comment]
@DerKleineLeif, do you mean something like [this](http://arduinolearning.com/code/arduino-ttp224-capacitive-touch-module.php)?

When you touch some button, then the button which is next also "gets pressed"? This produce false events, right?

**Comment by DerKleineLeif** [comment]
Yes thats the part we currently use. And yes it's quite small, so multiple buttons get pressed ... even with debounce ... causing unintended events. :(
I will wrap some code around  the block `//Check Buttons` in in `loop` procedure.

**Comment by wmarkow** [comment]
I do not know if there is a software way to fix this, because you only have a digital input from the sensor (two states). I have found [this datasheet](http://robojax.com/learn/arduino/robojax-TTP224_manual.pdf) but I took only a quick look at this. It is possible to set the sensitivity by changing the capacitors.

But I just have one idea. Currently you are touching this PCB at the specific place (buttons 1, 2, 3 or 4). What if your finger doesn't touch the PCB but is a few millimeters above? Will it be better then? When your finger doesn't touch the PCB then it will work like lowering the sensitivity of the device. Maybe you can cover the PCB with some 3mm plastic (or wooden?) card or something similar and then try it once again?
